packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: false
  unrs-resolver: true
  workerd: false
  prisma: true
  "@prisma/engines": true
  "@prisma/client": true
  "@parcel/watcher": true
  "@swc/core": true
